#!/bin/bash
#################################################################
# DVSwitch Server Installer by YO8AIV for Debian 12 (Bookworm)
# Compiles MMDVM_Bridge, Analog_Bridge, and md380-emu from source
# Features: Colored ASCII Banners, Error Handling, Systemd Integration
# Author: Generated by YO8AIV
# Date: June 2026
#################################################################

set -e # Exit on error

# --- Color Codes ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# --- Helper Functions ---

print_banner() {
    local text="$1"
    local color="$2"
    echo -e "${color}"
    echo "╔════════════════════════════════════════════════════════╗"
    echo "║                                                        ║"
    echo "║           ╷ ╷┌─┐┌─┐┌─┐╷╷ ╷                             ║"
    echo "║           └┬┘│ │├─┤├─┤││┌┘                             ║"
    echo "║            ╵ └─┘└─┘╵ ╵╵└┘                              ║"
    echo "║   D e b i a n   T r i x i e   I n s t a l l            ║"
    echo "║   O p t i m i z e d   b y     Y O 8 A I V    v.9       ║"
    echo "║                                                        ║"
    echo "╚════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_step() {
    local step="$1"
    echo -e "${CYAN}${BOLD}>>> $step${NC}"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (sudo)"
        exit 1
    fi
}

# --- Main Installation Logic ---

main() {
    check_root
    clear
    
    # Welcome Banner
    print_banner "DVSwitch Installer for Debian Bookworm" "$BLUE"
    echo "Starting installation process..."
    sleep 2

    # 1. Install Build Dependencies
    print_banner "Step 1: Installing Build Dependencies" "$GREEN"
    print_step "Updating package lists..."
    apt-get update -qq
    
    print_step "Installing core dependencies..."
    apt-get install -y git build-essential libssl-dev libcurl4-openssl-dev \
        libopus-dev libasound2-dev nodejs npm php-cli php-cgi lighttpd \
        spawn-fcgi libjsoncpp-dev systemd

    # Handle libctemplate-dev (often requires backports in Bookworm)
    print_step "Checking for libctemplate-dev..."
    if ! apt-get install -y libctemplate-dev; then
        echo -e "${YELLOW}Warning: libctemplate-dev not found in main repos.${NC}"
        echo "Attempting to install from bookworm-backports..."
        # Check if backports source exists, if not, warn user
        if ! grep -q "bookworm-backports" /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null; then
            log_error "Backports not enabled. Please enable 'bookworm-backports' in your sources.list and re-run."
            exit 1
        fi
        apt-get install -y -t bookworm-backports libctemplate-dev || {
            log_error "Failed to install libctemplate-dev. Installation cannot proceed."
            exit 1
        }
    fi

    # 2. Create Directory Structure
    print_banner "Step 2: Creating Directory Structure" "$CYAN"
    print_step "Creating directories in /opt and /var..."
    mkdir -p /opt/MMDVM_Bridge /opt/Analog_Bridge /opt/md380-emu
    mkdir -p /var/log/mmdvm /var/log/analog
    echo -e "${GREEN}Directories created successfully.${NC}"

    # 3. Compile MMDVM_Bridge
    print_banner "Step 3: Compiling MMDVM_Bridge" "$YELLOW"
    cd /tmp
    rm -rf MMDVM_Bridge
    print_step "Cloning repository..."
    git clone https://github.com/DVSwitch/MMDVM_Bridge.git
    cd MMDVM_Bridge/src
    print_step "Compiling source..."
    make clean
    make
    print_step "Installing binary and config..."
    cp MMDVM_Bridge /opt/MMDVM_Bridge/
    cp ../MMDVM_Bridge.ini /opt/MMDVM_Bridge/
    echo -e "${GREEN}MMDVM_Bridge compiled and installed.${NC}"

    # 4. Compile Analog_Bridge
    print_banner "Step 4: Compiling Analog_Bridge" "$YELLOW"
    cd /tmp
    rm -rf Analog_Bridge
    print_step "Cloning repository..."
    git clone https://github.com/DVSwitch/Analog_Bridge.git
    cd Analog_Bridge
    print_step "Compiling source..."
    make clean
    make
    print_step "Installing binary and config..."
    cp Analog_Bridge /opt/Analog_Bridge/
    cp Analog_Bridge.ini /opt/Analog_Bridge/
    echo -e "${GREEN}Analog_Bridge compiled and installed.${NC}"

    # 5. Compile md380-emu
    print_banner "Step 5: Compiling md380-emu" "$YELLOW"
    cd /tmp
    rm -rf md380-emu
    print_step "Cloning repository..."
    git clone https://github.com/DVSwitch/md380-emu.git
    cd md380-emu
    print_step "Compiling source..."
    make clean
    make
    print_step "Installing binary and config..."
    cp md380-emu /opt/md380-emu/
    cp md380-emu.ini /opt/md380-emu/
    echo -e "${GREEN}md380-emu compiled and installed.${NC}"

    # 6. Create Systemd Service Files
    print_banner "Step 6: Creating Systemd Services" "$BLUE"
    
    # MMDVM Bridge Service
    cat > /etc/systemd/system/mmdvm_bridge.service <<EOF
[Unit]
Description=MMDVM Bridge
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/MMDVM_Bridge
ExecStart=/opt/MMDVM_Bridge/MMDVM_Bridge MMDVM_Bridge.ini
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOF

    # Analog Bridge Service
    cat > /etc/systemd/system/analog_bridge.service <<EOF
[Unit]
Description=Analog Bridge
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/Analog_Bridge
ExecStart=/opt/Analog_Bridge/Analog_Bridge Analog_Bridge.ini
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOF

    # MD380 Emu Service
    cat > /etc/systemd/system/md380-emu.service <<EOF
[Unit]
Description=MD380 Emulator
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/md380-emu
ExecStart=/opt/md380-emu/md380-emu md380-emu.ini
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOF
    echo -e "${GREEN}Service files created.${NC}"

    # 7. Enable and Start Services
    print_banner "Step 7: Enabling and Starting Services" "$GREEN"
    print_step "Reloading systemd daemon..."
    systemctl daemon-reload
    print_step "Enabling services..."
    systemctl enable mmdvm_bridge analog_bridge md380-emu
    print_step "Starting services..."
    systemctl start mmdvm_bridge analog_bridge md380-emu
    
    # Check status briefly
    if systemctl is-active --quiet mmdvm_bridge && systemctl is-active --quiet analog_bridge; then
        echo -e "${GREEN}All services started successfully!${NC}"
    else
        echo -e "${YELLOW}Warning: One or more services may have failed to start. Check status below.${NC}"
    fi

    # 8. Final Instructions
    clear
    print_banner "Installation Complete!" "$GREEN"
    echo ""
    echo -e "${BOLD}Configuration files located at:${NC}"
    echo "  • /opt/MMDVM_Bridge/MMDVM_Bridge.ini"
    echo "  • /opt/Analog_Bridge/Analog_Bridge.ini"
    echo "  • /opt/md380-emu/md380-emu.ini"
    echo ""
    echo -e "${BOLD}Next Steps:${NC}"
    echo "  1. Edit the .ini files to set your DMR ID, Callsign, and Master Server."
    echo "  2. Restart services: ${CYAN}systemctl restart mmdvm_bridge analog_bridge md380-emu${NC}"
    echo "  3. Check status: ${CYAN}systemctl status mmdvm_bridge analog_bridge md380-emu${NC}"
    echo ""
    echo "73 de by YO8AIV"
}

# Run main function
main "$@"   
